### ISSUE TITLE
Failed to write to DisableAntiSpywareFailed to write to DisableRealTimeMonitoring

### ISSUE THREAD

**Issue by HubKing** [qtkite/defender-control#11]
It worked well on Windows 10, but it does not seem to work on Window 11. When I run it on Window 11, the output is:

```
failed to write to TamperProtection
Windows defender is currently ACTIVE
Failed to write to DisableAntiSpywareFailed to write to DisableRealTimeMonitoring
Disabled windows defender!
Press any key to continue . . .
```

It says that it has disabled Defender, but the MsMpEng/CP are still running. and real-time projection is still on.

![image](https://user-images.githubusercontent.com/10900489/153739456-1900eb6d-3264-47c6-b1cb-900ec0457d1f.png)

and next time I run defender-control, it still says the same output as above that includes "Windows defender is currently ACTIVE". I have rebooted the computer, but it was the same.

**Comment by qtkite** [comment]
can you post what version of 11 you are running? and any other information to replicate the issue?

**Comment by HubKing** [comment]
Never mind. I manually disabled "Temper protection" and run it again. This time it worked. It seems that the Temper projection was automatically on when upgraded from Win 10 to Win 11.
