### ISSUE TITLE
Failed to write to DisableAntiSpywareFailed to write to DisableRealTimeMonitoring

### ISSUE THREAD

**Issue by underwoodblog** [qtkite/defender-control#12]
Since latest Windows 10 Update, defender-control doesn't work anymore for me.

Error Message: "Failed to write to DisableAntiSpywareFailed to write to DisableRealTimeMonitoring"

**Comment by qtkite** [comment]
have you tried disabling tamper protection and running it again?

**Comment by underwoodblog** [comment]
I have disabled tamper protection, seems that it has be activated by the last update. Still the same error message but this time, it disabled windows defender.

Failed to write to DisableAntiSpywareFailed to write to DisableRealTimeMonitoring
Disabled windows defender!

**Comment by qtkite** [comment]
you can ignore the error

**Comment by underwoodblog** [comment]
Thanks for the fast help, so not only an update to 11 enables the tamper protection again.
