### ISSUE TITLE
Single program to disable & enable defender.

### ISSUE THREAD

**Issue by ggbbrr** [qtkite/defender-control#13]
Please, in the next version, release a single program that can either enable or disable defender. That is, if defender is active the program displays a message and asks if the user wants to disable it. And, if defender is disabled the program displays a message and asks the user if he wants to enable it.
Thanks for a nice program.

PS : A silent version would be nice too - basically toggle the state of defender.

**Comment by qtkite** [comment]
hi, a silent mode is already supported with the -s parameter. a ui is a wip atm, but i dont have time to constantly work on it - it is planned for 2.0 release
