### ISSUE TITLE
says access denied when writing registry values.

### ISSUE THREAD

**Issue by itsmepayback** [qtkite/defender-control#14]
Looks like TrustedInstaller cannot stop the windefend service anymore. It now says that it fails to stop the service and that it cannot write 
to TamperProtection, DisableRealTimeMonitoring, etc.

**Comment by qtkite** [comment]
hi, have you tried manually turning off tamper protection and running the program again? some other users ran into the same issue after a windows update

**Comment by itsmepayback** [comment]
Sorry. I haven't tried that. Its working now.
