### ISSUE TITLE
Not working after latest Windows 10 Update

### ISSUE THREAD

**Issue by galoko** [qtkite/defender-control#15]

**Comment by qtkite** [comment]
did you check the troubleshooting instructions in the readme?

**Comment by xnsweaty** [comment]
it sayes cant dollown it getting anoyying

**Comment by qtkite** [comment]
?

**Comment by qtkite** [comment]
disable windows defender + anti-tamper protection. then try downloading and running the disable-defender.exe

**Comment by xnsweaty** [comment]
i tryed

**Comment by xnsweaty** [comment]
it was working grear yesterday

**Comment by xnsweaty** [comment]
kept loading half way  then just closed

**Comment by xnsweaty** [comment]
i really dont know

**Comment by qtkite** [comment]
saying it doesn't work isnt really helpful. can you accurate describe what the error is and the troubleshooting steps you took

**Comment by xnsweaty** [comment]
i looked thought my setting all off the file loads half way

**Comment by qtkite** [comment]
what file are you talking about? huh

**Comment by xnsweaty** [comment]
im lost

**Comment by xnsweaty** [comment]
jjsploit

**Comment by qtkite** [comment]
i think your asking the wrong person

**Comment by xnsweaty** [comment]
who i ask

**Comment by qtkite** [comment]
this isnt a support page for your roblox cheats
