### ISSUE TITLE
"disable-defender.exe" Will Not Download

### ISSUE THREAD

**Issue by ImGoingToBakeMyGPU** [qtkite/defender-control#22]
Steps to Reproduce

1. Go to https://github.com/qtkite/defender-control/releases/tag/v1.2
2. click on "disable-defender.exe"
3. Get error "Faild-Download error"

**Comment by qtkite** [comment]
Disable browser security settings

**Comment by qtkite** [comment]
Also disable windows defender real-time protection to run
