### ISSUE TITLE
Windows 11 error

### ISSUE THREAD

**Issue by Clockworkx** [qtkite/defender-control#26]
![grafik](https://user-images.githubusercontent.com/40514153/198301894-ab1a382e-fcfa-40db-9607-17dd4f03c77e.png)

Started as administrator. Defender is not disabled.

**Comment by qtkite** [comment]
Did you try disable tamper protection manually as specified in the README.md?

**Comment by Clockworkx** [comment]
Wow, sorry. I used it the last time and it just worked.. But I had disabled temper protection manually there..
It was tamper protection! When I disabled it, it worked!

Thanks for the help
