### ISSUE TITLE
Feature Request: command line option for batch mode (don't wait for key press)

### ISSUE THREAD

**Issue by underwoodblog** [qtkite/defender-control#3]
Nice tool! Exactly what I was looking for. Thanks!

I like to disable defender in my backup batch script and enable it after backup is finished. Would be nice if the windows of defender-control is **not** waiting for a key press. With a command line option like -b for batch mode or a complete silent mode -s without a window?

Both (-disable/-enable) in one .exe via command line would be great too, so I only have to set exceptions for one file.

**Comment by qtkite** [comment]
Glad to see you like it!

Cool to see you make use of this program in a bash script, I will definitely take that into consideration for the next update to support arguments for a silent mode

**Comment by xHyperVoid** [comment]
hey ive been using the tool too! was wondering if theres a way as the guy above stated to have a silent mode?

**Comment by qtkite** [comment]
#9 Added here
