### ISSUE TITLE
Imggui files badly configured

### ISSUE THREAD

**Issue by itsmepayback** [qtkite/defender-control#8]
I am trying to compile your code in visual studio 2022 but it says that imgui.h file and other .h files related to imgui files are not there.
As I explored the repository, I figured they are in the imgui folder. But even if they are here, it still says it cannot find them when compiling. Can you help with that?

**Comment by qtkite** [comment]
did you even set the build output to Release mode and x64 platform?

**Comment by itsmepayback** [comment]
Yes i did set it as release and kept it as x64 platform but it still cannot find the imgui files

**Comment by qtkite** [comment]
It probably somehow unlinked itself in your solution settings. I re-cloned it and tested and it compiles fine. try that or just relink the imgui files in your solution settings.

**Comment by itsmepayback** [comment]
okay, relinking the imgui header files seems to compile fine. But why didn't you also made an x86 version for compatibility?

**Comment by qtkite** [comment]
i don’t care about x86

**Comment by itsmepayback** [comment]
ok lol

**Comment by qtkite** [comment]
> okay, relinking the imgui header files seems to compile fine. But why didn't you also made an x86 version for compatibility?

x86 requires different flags for setting certain registries. doing everything x64 is easier.
