### ISSUE TITLE
Remove prompts and run it silently? 

### ISSUE THREAD

**Issue by xHyperVoid** [qtkite/defender-control#9]
Hi, I just started out in github im wondering if you can add a feature so we can run them in silent without the prompts?
maybe add start arguments as "-s" to run it silently?
or have it run in cmd  as like "disable-defender.exe -silent"

**Comment by xHyperVoid** [comment]
I figured it out now by just checking the .sln project
What i did is basically
Deleted Gui
Changed main.cpp line 55 to system("exit")

Building it runs the .exe without prompts

**Comment by qtkite** [comment]
this works but its better to just comment out the system call

**Comment by qtkite** [comment]
Added in the latest release. Launch disable-defender.exe with -s argument from an elevated shell.
